### ISSUE TITLE
reference is invalid

### ISSUE THREAD

**Issue by matzew** [knative-extensions/kn-plugin-event#305]
Error when sending  message to `main` from kafka-broker.

I am getting:
```
kn-event-linux-amd64 -n knative-eventing send \
  --to Broker:eventing.knative.dev/v1:my-demo-kafka-broker \
  --type demo.new \
  -f message="fooss"
Error: can't sent event: reference is invalid: resource isn't addressable: failed to get object knative-eventing/my-demo-kafka-broker: brokers.eventing.knative.dev "my-demo-kafka-broker" not found
```

**Comment by matzew** [comment]
here is the status:

```
status:
  address:
    name: http
    url: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/my-demo-kafka-broker
  addresses:
  - name: http
    url: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/my-demo-kafka-broker
```
